site_name: "Xichen Pan's Homepage"
site_author: 'Xichen Pan'
copyright: '&copy; 2022-2023 Xichen Pan'
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: white
    accent: amber
  favicon: images/favicon.png
  icon:
    logo: material/account-school
  features:
    - content.action.edit
    
plugins:
  []
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra:
  social:
    - icon: fontawesome/solid/envelope 
      link: mailto:xcpan.mail@gmail.com
    - icon: academicons/google-scholar
      link: https://scholar.google.com/citations?user=9wh9VXIAAAAJ&hl=en
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/xichenpan/
    - icon: fontawesome/brands/github 
      link: https://github.com/Flash-321
    - icon: fontawesome/brands/zhihu 
      link: https://www.zhihu.com/people/pan-xi-chen-54
    - icon: academicons/cv
      link: sources/Xichen_CV.pdf
  analytics:
    provider: google
    property: G-KBQPT9Q9MJ

extra_css:
  - stylesheets/extra.css 
